window.OWNEX = {
  "exhibitions": [
    {
      "collected_date": "2026-09-01",
      "title": "〈2026 화성 연대기 탐사보고회〉교육프로그램서울시립 북서울미술관상시2026/09/14 까지 모집",
      "venue": "서울시립미술관",
      "venue_address": "서울 중구 덕수궁길 61 (시청·서소문)",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-09-18",
      "end_date": "2026-09-18",
      "reservation_open_date": "2026-09-11",
      "summary": "북서울미술관",
      "image_url": "https://sema.seoul.go.kr/common/imgFileView?thumbYn=N&FILE_ID=1016022",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "주요미술관, 지정미술관",
      "has_art": true,
      "poster": "posters/9b3494bb846c.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "구정아: 우스모스",
      "venue": "리움미술관",
      "venue_address": "서울 용산구 이태원로55길 60-16",
      "region_tag": "[서울]",
      "reservation_url": "https://www.leeum.org/",
      "start_date": "2026-09-05",
      "end_date": "2026-12-27",
      "reservation_open_date": "2026-08-29",
      "summary": "리움미술관",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.leeum.org/",
      "score_reason": "3곳포털홍보, 국내선호:구정아, 구정아, 아시아작가:구정아, 개인전, 작가작품전, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/099dd604d708.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "키아프·프리즈 서울 2026",
      "venue": "코엑스",
      "venue_address": "서울 강남구 영동대로 513",
      "region_tag": "[서울]",
      "reservation_url": "https://mediahub.seoul.go.kr/archives/2019208",
      "start_date": "2026-09-02",
      "end_date": "2026-09-06",
      "reservation_open_date": "2026-08-26",
      "summary": "키아프·프리즈 서울 2026",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31004942/20260830154941-20260830_154941.jpg",
      "source_urls": "https://mediahub.seoul.go.kr/archives/2019208",
      "score_reason": "3곳포털홍보, 주요미술관, 화제전시, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/256846bd32a6.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "솔 르윗: Open Structure",
      "venue": "아모레퍼시픽미술관",
      "venue_address": "서울 용산구 한강대로 100",
      "region_tag": "[서울]",
      "reservation_url": "https://www.apma.amorepacific.com/",
      "start_date": "2026-09-01",
      "end_date": "2027-02-28",
      "reservation_open_date": "2026-08-25",
      "summary": "아모레퍼시픽미술관",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31011722/20260830161718-Frieze-Seoul-2025-10.jpg",
      "source_urls": "https://www.apma.amorepacific.com/",
      "score_reason": "3곳포털홍보, 세계인기:솔 르윗, 솔 르윗, 근현대, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/d3d5464b1ce4.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "서도호",
      "venue": "국립현대미술관 서울",
      "venue_address": "서울 종로구 삼청로 30",
      "region_tag": "[서울]",
      "reservation_url": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "start_date": "2026-08-27",
      "end_date": "2027-02-09",
      "reservation_open_date": "2026-08-20",
      "summary": "현대미술 국립현대미술관",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "score_reason": "3곳포털홍보, 국내선호:서도호, 서도호, 아시아작가:서도호, 현대미술, 작가작품전, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/450cdd8ee85f.jpg"
    },
    {
      "collected_date": "2026-09-02",
      "title": "윤형근을 다시 상상하다",
      "venue": "PKM갤러리",
      "venue_address": "서울 종로구 삼청로7길 40",
      "region_tag": "[서울]",
      "reservation_url": "https://www.pkmgallery.com/",
      "start_date": "2026-08-26",
      "end_date": "2026-10-03",
      "reservation_open_date": "2026-08-19",
      "summary": "윤형근을 다시 상상하다",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.pkmgallery.com/",
      "score_reason": "대표작품, 2곳홍보, 국내선호:윤형근, 단색화, 작가작품전, 화제전시, 주요뉴스, 서울",
      "has_art": true,
      "poster": "posters/ab93482f4eef.jpg"
    },
    {
      "collected_date": "2026-09-02",
      "title": "김보희: TOWARDS There Was Light",
      "venue": "갤러리현대",
      "venue_address": "서울 종로구 삼청로 14",
      "region_tag": "[서울]",
      "reservation_url": "https://www.galleryhyundai.com/",
      "start_date": "2026-08-26",
      "end_date": "2026-10-18",
      "reservation_open_date": "2026-08-19",
      "summary": "김보희: TOWARDS There Was Light",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.galleryhyundai.com/",
      "score_reason": "시각자료, 대표작품, 2곳홍보, 회화전, 작가작품전, 화제전시, 주요뉴스, 서울",
      "has_art": true,
      "poster": "posters/32087c00bfc3.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "박서보: 변하는 변하지 않는",
      "venue": "국제갤러리",
      "venue_address": "서울 종로구 삼청로 54",
      "region_tag": "[서울]",
      "reservation_url": "https://www.kukjegallery.com/",
      "start_date": "2026-08-24",
      "end_date": "2026-10-18",
      "reservation_open_date": "2026-08-17",
      "summary": "박서보: 변하는 변하지 않는",
      "image_url": "https://www.kukjegallery.com/upload/promotion/31342bbe2e88fe777a2a5150854b445a_thumb_1580x2000.jpg",
      "source_urls": "https://www.kukjegallery.com/",
      "score_reason": "3곳포털홍보, 국내선호:박서보, 박서보, 아시아작가:박서보, 단색화, 작가작품전, 주요미술관, 화제전시, 가볼만함, 지정미술관",
      "has_art": true,
      "poster": "posters/1a7d9f8a8b46.jpg"
    },
    {
      "collected_date": "2026-09-02",
      "title": "김희천: 두더지들",
      "venue": "서울시립 서서울미술관",
      "venue_address": "서울 금천구 시흥대로79길 65",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-08-20",
      "end_date": "2026-11-08",
      "reservation_open_date": "2026-08-13",
      "summary": "서서울미술관",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31011722/20260830161718-Frieze-Seoul-2025-10.jpg",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "시각자료, 대표작품, 2곳홍보, 동시대, 작가작품전, 주요미술관, 화제전시, 지정미술관",
      "has_art": true,
      "poster": "posters/1673f8139b1f.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "게오르그 바젤리츠",
      "venue": "세화미술관",
      "venue_address": "서울 종로구 새문안로 68 흥국생명빌딩",
      "region_tag": "[서울]",
      "reservation_url": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "start_date": "2026-08-13",
      "end_date": "2026-12-27",
      "reservation_open_date": "2026-08-06",
      "summary": "세화미술관",
      "image_url": "https://sehwamuseum.org/wp-content/uploads/2026/08/20260826_000037.jpg",
      "source_urls": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "score_reason": "3곳포털홍보, 세계인기:바젤리츠, 바젤리츠, 근현대, 작가작품전, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/543ddb01f576.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "가우디: 서울에서 다시 태어나다",
      "venue": "신사하우스",
      "venue_address": "서울 강남구 강남대로162길 27",
      "region_tag": "[서울]",
      "reservation_url": "https://gaudiseoul.com/",
      "start_date": "2026-08-01",
      "end_date": "2026-10-31",
      "reservation_open_date": "2026-07-25",
      "summary": "르네상스",
      "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/ef/SF_maig_2_cropped.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://gaudiseoul.com/",
      "score_reason": "3곳포털홍보, 세계인기:가우디, 가우디, 르네상스, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/49ce0c8acc7b.jpg"
    },
    {
      "collected_date": "2026-09-02",
      "title": "함양아: 정의되지 않은 파노라마",
      "venue": "아트선재센터",
      "venue_address": "서울 종로구 율곡로3길 87",
      "region_tag": "[서울]",
      "reservation_url": "https://www.artsonje.org/",
      "start_date": "2026-07-31",
      "end_date": "2026-10-04",
      "reservation_open_date": "2026-07-24",
      "summary": "함양아: 정의되지 않은 파노라마",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.artsonje.org/",
      "score_reason": "시각자료, 2곳홍보, 근현대, 작가작품전, 주요미술관, 화제전시, 주요뉴스, 서울",
      "has_art": true,
      "poster": "posters/99efce9ff693.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "뱅크시 : Still Here",
      "venue": "더현대 서울 ALT.1",
      "venue_address": "서울 영등포구 여의대로 108 여의도 6층",
      "region_tag": "[서울]",
      "reservation_url": "https://korean.visitseoul.net/exhibition/BANKSY-still-here/KOPx0x7wx",
      "start_date": "2026-07-22",
      "end_date": "2026-11-03",
      "reservation_open_date": "2026-07-15",
      "summary": "현대미술",
      "image_url": "https://upload.wikimedia.org/wikipedia/en/7/77/Girl_with_balloon.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://korean.visitseoul.net/exhibition/BANKSY-still-here/KOPx0x7wx",
      "score_reason": "3곳포털홍보, 세계인기:뱅크시, 국내선호:뱅크시, 뱅크시, 현대미술, 미술사가치, 주요미술관, 화제전시, 가볼만함, 지정미술관",
      "has_art": true,
      "poster": "posters/be8cb790b126.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "큐비스트: 시각의 혁신가들",
      "venue": "퐁피두센터 한화",
      "venue_address": "서울 영등포구 63로 50 여의도 63빌딩",
      "region_tag": "[서울]",
      "reservation_url": "https://www.centrepompidou-hanwha.kr/",
      "start_date": "2026-06-04",
      "end_date": "2026-10-04",
      "reservation_open_date": "2026-05-28",
      "summary": "큐비스트: 시각의 혁신가들",
      "image_url": "https://upload.wikimedia.org/wikipedia/en/1/1c/Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://www.centrepompidou-hanwha.kr/",
      "score_reason": "큐비스트, 주요미술관, 지정미술관",
      "has_art": true,
      "poster": "posters/865151bf8c7f.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "(일본) 해외 한국문화원 순회전 《나전장의 도안실》",
      "venue": "서울공예박물관",
      "venue_address": "서울 종로구 율곡로 396 안국",
      "region_tag": "[서울]",
      "reservation_url": "https://craftmuseum.seoul.go.kr/",
      "start_date": "2026-06-04",
      "end_date": "2026-10-24",
      "reservation_open_date": "2026-05-28",
      "summary": "서울공예박물관",
      "image_url": "https://craftmuseum.seoul.go.kr/common/program/filedown?idx=2064",
      "source_urls": "https://craftmuseum.seoul.go.kr/",
      "score_reason": "주요미술관, 지정미술관",
      "has_art": true,
      "poster": "posters/351107469824.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "유영국: 산은 내 안에 있다",
      "venue": "서울시립미술관 서소문본관",
      "venue_address": "서울 중구 덕수궁길 61",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-05-19",
      "end_date": "2026-10-25",
      "reservation_open_date": "2026-05-12",
      "summary": "추상 서울시립미술관",
      "image_url": "https://sema.seoul.go.kr/common/imgFileView?thumbYn=Y&FILE_ID=1016701",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "3곳포털홍보, 국내선호:유영국, 유영국, 아시아작가:유영국, 추상, 작가작품전, 주요미술관, 화제전시, 주요뉴스, 지정미술관",
      "has_art": true,
      "poster": "posters/27eee08a553e.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "건축투어 2026",
      "venue": "DDP 동대문디자인플라자",
      "venue_address": "서울 중구 을지로 281",
      "region_tag": "[서울]",
      "reservation_url": "https://www.ddp.or.kr/",
      "start_date": "2026-03-21",
      "end_date": "2026-12-31",
      "reservation_open_date": "2026-03-14",
      "summary": "건축투어 2026",
      "image_url": "https://www.ddp.or.kr/usr/upload/board_thumb/zboardphotogallery8/20260708045900300.jpg",
      "source_urls": "https://www.ddp.or.kr/",
      "score_reason": "주요미술관, 지정미술관",
      "has_art": true,
      "poster": "posters/714f9b024d24.jpg"
    },
    {
      "collected_date": "2026-09-01",
      "title": "漆-옻나무에서 칠기로",
      "venue": "서울공예박물관",
      "venue_address": "서울 종로구 율곡로 396 안국",
      "region_tag": "[서울]",
      "reservation_url": "https://craftmuseum.seoul.go.kr/",
      "start_date": "2025-06-27",
      "end_date": "2026-12-31",
      "reservation_open_date": "2025-06-20",
      "summary": "서울공예박물관",
      "image_url": "https://craftmuseum.seoul.go.kr/common/program/filedown?idx=2064",
      "source_urls": "https://craftmuseum.seoul.go.kr/",
      "score_reason": "주요미술관, 지정미술관",
      "has_art": true,
      "poster": "posters/3c13cdb23009.jpg"
    }
  ],
  "email": [
    {
      "collected_date": "2026-09-04",
      "title": "큐비스트: 시각의 혁신가들",
      "venue": "퐁피두센터 한화",
      "venue_address": "서울 영등포구 63로 50",
      "region_tag": "[서울]",
      "reservation_url": "https://www.centrepompidou-hanwha.kr/",
      "start_date": "2026-06-04",
      "end_date": "2026-10-04",
      "reservation_open_date": "2026-05-28",
      "summary": "피카소 르네상스",
      "image_url": "https://upload.wikimedia.org/wikipedia/en/1/1c/Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://www.centrepompidou-hanwha.kr/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 세계인기:피카소, 피카소, 르네상스, 작가작품전, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "서도호",
      "venue": "국립현대미술관 서울",
      "venue_address": "서울 종로구 삼청로 30",
      "region_tag": "[서울]",
      "reservation_url": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "start_date": "2026-08-27",
      "end_date": "2027-02-09",
      "reservation_open_date": "2026-08-20",
      "summary": "현대미술 국립현대미술관",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "score_reason": "시각자료, 3곳포털홍보, 국내선호:서도호, 서도호, 아시아작가:서도호, 현대미술, 작가작품전, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "게오르그 바젤리츠",
      "venue": "세화미술관",
      "venue_address": "서울 종로구 새문안로 68 흥국생명빌딩",
      "region_tag": "[서울]",
      "reservation_url": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "start_date": "2026-08-13",
      "end_date": "2026-12-27",
      "reservation_open_date": "2026-08-06",
      "summary": "세화미술관",
      "image_url": "https://sehwamuseum.org/wp-content/uploads/2026/08/20260826_000037.jpg",
      "source_urls": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 세계인기:바젤리츠, 바젤리츠, 근현대, 작가작품전, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "박서보: 변하는 변하지 않는",
      "venue": "국제갤러리",
      "venue_address": "서울 종로구 삼청로 54",
      "region_tag": "[서울]",
      "reservation_url": "https://www.kukjegallery.com/",
      "start_date": "2026-08-24",
      "end_date": "2026-10-18",
      "reservation_open_date": "2026-08-17",
      "summary": "박서보: 변하는 변하지 않는",
      "image_url": "https://www.kukjegallery.com/upload/promotion/31342bbe2e88fe777a2a5150854b445a_thumb_1580x2000.jpg",
      "source_urls": "https://www.kukjegallery.com/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 국내선호:박서보, 박서보, 아시아작가:박서보, 단색화, 작가작품전, 주요미술관, 화제전시, 가볼만함, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "유영국: 산은 내 안에 있다",
      "venue": "서울시립미술관 서소문본관",
      "venue_address": "서울 중구 덕수궁길 61",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-05-19",
      "end_date": "2026-10-25",
      "reservation_open_date": "2026-05-12",
      "summary": "추상 서울시립미술관",
      "image_url": "https://sema.seoul.go.kr/common/imgFileView?thumbYn=Y&FILE_ID=1016701",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 국내선호:유영국, 유영국, 아시아작가:유영국, 추상, 작가작품전, 주요미술관, 화제전시, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "구정아: 우스모스",
      "venue": "리움미술관",
      "venue_address": "서울 용산구 이태원로55길 60-16",
      "region_tag": "[서울]",
      "reservation_url": "https://www.leeum.org/",
      "start_date": "2026-09-05",
      "end_date": "2026-12-27",
      "reservation_open_date": "2026-08-29",
      "summary": "리움미술관",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.leeum.org/",
      "score_reason": "시각자료, 3곳포털홍보, 국내선호:구정아, 구정아, 아시아작가:구정아, 개인전, 작가작품전, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "뱅크시 : Still Here",
      "venue": "더현대 서울 ALT.1",
      "venue_address": "서울 영등포구 여의대로 108 여의도 6층",
      "region_tag": "[서울]",
      "reservation_url": "https://korean.visitseoul.net/exhibition/BANKSY-still-here/KOPx0x7wx",
      "start_date": "2026-07-22",
      "end_date": "2026-11-03",
      "reservation_open_date": "2026-07-15",
      "summary": "현대미술",
      "image_url": "https://upload.wikimedia.org/wikipedia/en/7/77/Girl_with_balloon.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://korean.visitseoul.net/exhibition/BANKSY-still-here/KOPx0x7wx",
      "score_reason": "시각자료, 3곳포털홍보, 세계인기:뱅크시, 국내선호:뱅크시, 뱅크시, 현대미술, 미술사가치, 주요미술관, 화제전시, 가볼만함, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "가우디: 서울에서 다시 태어나다",
      "venue": "신사하우스",
      "venue_address": "서울 강남구 강남대로162길 27",
      "region_tag": "[서울]",
      "reservation_url": "https://gaudiseoul.com/",
      "start_date": "2026-08-01",
      "end_date": "2026-10-31",
      "reservation_open_date": "2026-07-25",
      "summary": "르네상스",
      "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/ef/SF_maig_2_cropped.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://gaudiseoul.com/",
      "score_reason": "시각자료, 3곳포털홍보, 세계인기:가우디, 가우디, 르네상스, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "솔 르윗: Open Structure",
      "venue": "아모레퍼시픽미술관",
      "venue_address": "서울 용산구 한강대로 100",
      "region_tag": "[서울]",
      "reservation_url": "https://www.apma.amorepacific.com/",
      "start_date": "2026-09-01",
      "end_date": "2027-02-28",
      "reservation_open_date": "2026-08-25",
      "summary": "아모레퍼시픽미술관",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31011722/20260830161718-Frieze-Seoul-2025-10.jpg",
      "source_urls": "https://www.apma.amorepacific.com/",
      "score_reason": "시각자료, 3곳포털홍보, 세계인기:솔 르윗, 솔 르윗, 근현대, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "윤형근을 다시 상상하다",
      "venue": "PKM갤러리",
      "venue_address": "서울 종로구 삼청로7길 40",
      "region_tag": "[서울]",
      "reservation_url": "https://www.pkmgallery.com/",
      "start_date": "2026-08-26",
      "end_date": "2026-10-03",
      "reservation_open_date": "2026-08-19",
      "summary": "윤형근을 다시 상상하다",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.pkmgallery.com/",
      "score_reason": "시각자료, 대표작품, 2곳홍보, 국내선호:윤형근, 단색화, 작가작품전, 화제전시, 주요뉴스, 서울"
    },
    {
      "collected_date": "2026-09-04",
      "title": "김보희: TOWARDS There Was Light",
      "venue": "갤러리현대",
      "venue_address": "서울 종로구 삼청로 14",
      "region_tag": "[서울]",
      "reservation_url": "https://www.galleryhyundai.com/",
      "start_date": "2026-08-26",
      "end_date": "2026-10-18",
      "reservation_open_date": "2026-08-19",
      "summary": "김보희: TOWARDS There Was Light",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.galleryhyundai.com/",
      "score_reason": "시각자료, 대표작품, 2곳홍보, 회화전, 작가작품전, 화제전시, 주요뉴스, 서울"
    },
    {
      "collected_date": "2026-09-04",
      "title": "김희천: 두더지들",
      "venue": "서울시립 서서울미술관",
      "venue_address": "서울 금천구 시흥대로79길 65",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-08-20",
      "end_date": "2026-11-08",
      "reservation_open_date": "2026-08-13",
      "summary": "서서울미술관",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31011722/20260830161718-Frieze-Seoul-2025-10.jpg",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "시각자료, 대표작품, 2곳홍보, 동시대, 작가작품전, 주요미술관, 화제전시, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "함양아: 정의되지 않은 파노라마",
      "venue": "아트선재센터",
      "venue_address": "서울 종로구 율곡로3길 87",
      "region_tag": "[서울]",
      "reservation_url": "https://www.artsonje.org/",
      "start_date": "2026-07-31",
      "end_date": "2026-10-04",
      "reservation_open_date": "2026-07-24",
      "summary": "함양아: 정의되지 않은 파노라마",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.artsonje.org/",
      "score_reason": "시각자료, 2곳홍보, 근현대, 작가작품전, 주요미술관, 화제전시, 주요뉴스, 서울"
    },
    {
      "collected_date": "2026-09-04",
      "title": "키아프·프리즈 서울 2026",
      "venue": "코엑스",
      "venue_address": "서울 강남구 영동대로 513",
      "region_tag": "[서울]",
      "reservation_url": "https://mediahub.seoul.go.kr/archives/2019208",
      "start_date": "2026-09-02",
      "end_date": "2026-09-06",
      "reservation_open_date": "2026-08-26",
      "summary": "키아프·프리즈 서울 2026",
      "image_url": "https://design-plus.storage.googleapis.com/wp-content/uploads/2026/08/31004942/20260830154941-20260830_154941.jpg",
      "source_urls": "https://mediahub.seoul.go.kr/archives/2019208",
      "score_reason": "시각자료, 3곳포털홍보, 주요미술관, 화제전시, 주요뉴스, 지정미술관"
    }
  ],
  "calendar": [
    {
      "collected_date": "2026-09-04",
      "title": "큐비스트: 시각의 혁신가들",
      "venue": "퐁피두센터 한화",
      "venue_address": "서울 영등포구 63로 50",
      "region_tag": "[서울]",
      "reservation_url": "https://www.centrepompidou-hanwha.kr/",
      "start_date": "2026-06-04",
      "end_date": "2026-10-04",
      "reservation_open_date": "2026-05-28",
      "summary": "피카소 르네상스",
      "image_url": "https://upload.wikimedia.org/wikipedia/en/1/1c/Pablo_Picasso%2C_1910%2C_Girl_with_a_Mandolin_%28Fanny_Tellier%29%2C_oil_on_canvas%2C_100.3_x_73.6_cm%2C_Museum_of_Modern_Art_New_York..jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled",
      "source_urls": "https://www.centrepompidou-hanwha.kr/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 세계인기:피카소, 피카소, 르네상스, 작가작품전, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "서도호",
      "venue": "국립현대미술관 서울",
      "venue_address": "서울 종로구 삼청로 30",
      "region_tag": "[서울]",
      "reservation_url": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "start_date": "2026-08-27",
      "end_date": "2027-02-09",
      "reservation_open_date": "2026-08-20",
      "summary": "현대미술 국립현대미술관",
      "image_url": "https://k-artnow.com/data/content/2026/08/6_0a09c8844ba8f0936c20bd791130d6b6.jpg",
      "source_urls": "https://www.mmca.go.kr/exhibits/exhibitsList.do",
      "score_reason": "시각자료, 3곳포털홍보, 국내선호:서도호, 서도호, 아시아작가:서도호, 현대미술, 작가작품전, 미술사가치, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "게오르그 바젤리츠",
      "venue": "세화미술관",
      "venue_address": "서울 종로구 새문안로 68 흥국생명빌딩",
      "region_tag": "[서울]",
      "reservation_url": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "start_date": "2026-08-13",
      "end_date": "2026-12-27",
      "reservation_open_date": "2026-08-06",
      "summary": "세화미술관",
      "image_url": "https://sehwamuseum.org/wp-content/uploads/2026/08/20260826_000037.jpg",
      "source_urls": "https://sehwamuseum.org/exhibition/%ea%b2%8c%ec%98%a4%eb%a5%b4%ea%b7%b8-%eb%b0%94%ec%a0%a4%eb%a6%ac%ec%b8%a0/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 세계인기:바젤리츠, 바젤리츠, 근현대, 작가작품전, 주요미술관, 화제전시, 가볼만함, 주요뉴스, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "박서보: 변하는 변하지 않는",
      "venue": "국제갤러리",
      "venue_address": "서울 종로구 삼청로 54",
      "region_tag": "[서울]",
      "reservation_url": "https://www.kukjegallery.com/",
      "start_date": "2026-08-24",
      "end_date": "2026-10-18",
      "reservation_open_date": "2026-08-17",
      "summary": "박서보: 변하는 변하지 않는",
      "image_url": "https://www.kukjegallery.com/upload/promotion/31342bbe2e88fe777a2a5150854b445a_thumb_1580x2000.jpg",
      "source_urls": "https://www.kukjegallery.com/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 국내선호:박서보, 박서보, 아시아작가:박서보, 단색화, 작가작품전, 주요미술관, 화제전시, 가볼만함, 지정미술관"
    },
    {
      "collected_date": "2026-09-04",
      "title": "유영국: 산은 내 안에 있다",
      "venue": "서울시립미술관 서소문본관",
      "venue_address": "서울 중구 덕수궁길 61",
      "region_tag": "[서울]",
      "reservation_url": "https://sema.seoul.go.kr/",
      "start_date": "2026-05-19",
      "end_date": "2026-10-25",
      "reservation_open_date": "2026-05-12",
      "summary": "추상 서울시립미술관",
      "image_url": "https://sema.seoul.go.kr/common/imgFileView?thumbYn=Y&FILE_ID=1016701",
      "source_urls": "https://sema.seoul.go.kr/",
      "score_reason": "시각자료, 대표작품, 3곳포털홍보, 국내선호:유영국, 유영국, 아시아작가:유영국, 추상, 작가작품전, 주요미술관, 화제전시, 주요뉴스, 지정미술관"
    }
  ],
  "google": {
    "connected": true,
    "name": "Ownex",
    "events": [
      {
        "title": "큐비스트: 시각의 혁신가들",
        "start": "2026-09-04",
        "end": "2026-10-05",
        "location": "퐁피두센터 한화 서울 영등포구 63로 50",
        "html_link": "https://www.google.com/calendar/event?eid=ZHIyODBsY3BxcmNncWN1azNnbjBoOWYyZXMgYjAzYTNlNDFlNTFmODZlYzZlNjUzNGIzOTM2MTVkODZjYThkY2UzYmVlNTJkM2ZlYmNkNGE4NzljNThiM2IxM0Bn"
      },
      {
        "title": "서도호",
        "start": "2026-09-04",
        "end": "2027-02-10",
        "location": "국립현대미술관 서울 서울 종로구 삼청로 30",
        "html_link": "https://www.google.com/calendar/event?eid=ZWltbWZkaTgwbnB1OG0zMjhubjQ0aGw4czAgYjAzYTNlNDFlNTFmODZlYzZlNjUzNGIzOTM2MTVkODZjYThkY2UzYmVlNTJkM2ZlYmNkNGE4NzljNThiM2IxM0Bn"
      },
      {
        "title": "게오르그 바젤리츠",
        "start": "2026-09-04",
        "end": "2026-12-28",
        "location": "세화미술관 서울 종로구 새문안로 68 흥국생명빌딩",
        "html_link": "https://www.google.com/calendar/event?eid=Njc1dXZ2djZmcWg0OW5yYjd0dDF2cjFzc28gYjAzYTNlNDFlNTFmODZlYzZlNjUzNGIzOTM2MTVkODZjYThkY2UzYmVlNTJkM2ZlYmNkNGE4NzljNThiM2IxM0Bn"
      },
      {
        "title": "박서보: 변하는 변하지 않는",
        "start": "2026-09-04",
        "end": "2026-10-19",
        "location": "국제갤러리 서울 종로구 삼청로 54",
        "html_link": "https://www.google.com/calendar/event?eid=bTJnMmoxZjEyZDlwOGlzamdkOGQ0cTVoYjggYjAzYTNlNDFlNTFmODZlYzZlNjUzNGIzOTM2MTVkODZjYThkY2UzYmVlNTJkM2ZlYmNkNGE4NzljNThiM2IxM0Bn"
      },
      {
        "title": "유영국: 산은 내 안에 있다",
        "start": "2026-09-04",
        "end": "2026-10-26",
        "location": "서울시립미술관 서소문본관 서울 중구 덕수궁길 61",
        "html_link": "https://www.google.com/calendar/event?eid=Nzg0YWJtOGcxNXNwdHBqc2RrN2VqbWZuZjQgYjAzYTNlNDFlNTFmODZlYzZlNjUzNGIzOTM2MTVkODZjYThkY2UzYmVlNTJkM2ZlYmNkNGE4NzljNThiM2IxM0Bn"
      }
    ],
    "embed_src": "https://calendar.google.com/calendar/embed?src=b03a3e41e51f86ec6e6534b393615d86ca8dce3bee52d3febcd4a879c58b3b13@group.calendar.google.com&ctz=Asia/Seoul&mode=MONTH&showPrint=0&showTz=0&showCalendars=0&bgcolor=%23D7EFFF",
    "open_url": "https://calendar.google.com/calendar/u/0/r?cid=b03a3e41e51f86ec6e6534b393615d86ca8dce3bee52d3febcd4a879c58b3b13@group.calendar.google.com"
  },
  "saved": {
    "rev": "6stickers",
    "notes": {
      "윤형근을 다시 상상하다|PKM갤러리|2026-08-26|2026-10-03": {
        "visited": false,
        "at": "2026-09-03"
      },
      "구정아: 우스모스|리움미술관|2026-09-05|2026-12-27": {
        "visited": true,
        "at": "2026-09-03"
      },
      "가우디: 서울에서 다시 태어나다|신사하우스|2026-08-01|2026-10-31": {
        "visited": true,
        "at": "2026-09-03"
      },
      "게오르그 바젤리츠|세화미술관|2026-08-13|2026-12-27": {
        "visited": true,
        "at": "2026-09-03"
      },
      "뱅크시 : Still Here|더현대 서울 ALT.1|2026-07-22|2026-11-03": {
        "visited": true,
        "at": "2026-09-03"
      },
      "박서보: 변하는 변하지 않는|국제갤러리|2026-08-24|2026-10-18": {
        "visited": true,
        "at": "2026-09-03"
      },
      "큐비스트: 시각의 혁신가들|퐁피두센터 한화|2026-06-04|2026-10-04": {
        "visited": true,
        "at": "2026-09-03"
      },
      "김희천: 두더지들|서울시립 서서울미술관|2026-08-20|2026-11-08": {
        "visited": false,
        "at": "2026-09-03"
      }
    },
    "feels": [
      {
        "id": "seed-cubist",
        "title": "큐비스트 감상",
        "body": "유럽의 거장 큐비스트들을 통해 한국의 나헤석, 김환기 작가 등 한국 근현대 미술가들이 오버랩되어 한국의 큐비즘의 태동을 만난 것 같았다.",
        "at": "2026-09-03",
        "showId": "큐비스트: 시각의 혁신가들|퐁피두센터 한화|2026-06-04|2026-10-04"
      },
      {
        "id": "1788479088443",
        "title": "김희천: 두더지들",
        "body": "바쁜 현대 사회를 살아 가면서 잠깐 빠져 나오게\n해 주는 작품이었습니다.",
        "at": "2026-09-03",
        "showId": "김희천: 두더지들|서울시립 서서울미술관|2026-08-20|2026-11-08"
      }
    ]
  }
};
